apiVersion: v1
kind: Secret
metadata:
  name: secret-elastic
type: Opaque
stringData:
  cluster: "https://286ee92d6626453e85c5f75ac669943b.eu-central-1.aws.cloud.es.io:9243"
  http.auth: "elastic:B19poF8tZo4scnZ0RreqRItG"
